name: Publish release summary to discord

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: LeGitHubDeTai/github-to-discord@main
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Steamship Release Bot
          DISCORD_AVATAR: https://www.steamship.com/images/brand/steamship-logo-light-symbol.png
          MESSAGE_TITLE: New python-client release
          MESSAGE_DESCRIPTION: New Release of the python-client
          MESSAGE_URL: https://github.com/steamship-core/python-client/releases
          MESSAGE_COLOR: 5814783
